sudo: required
services:
  - docker

before_install:
  - docker build -t taemin19/docker-react-demo -f Dockerfile.dev .

script:
  - docker run taemin19/docker-react-demo npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-demo"
  env: "DockerReactDemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-665903715408"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
